/*
=========================================================
Retail Intelligence Platform
Migration: V002
Purpose: Create the Identity domain
Tables:
  1. identity.customers
  2. identity.credentials
  3. identity.addresses
=========================================================
*/

/*
=========================================================
CUSTOMERS
=========================================================
*/

CREATE TABLE identity.customers (
    customer_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    first_name VARCHAR(100)
        NOT NULL,

    last_name VARCHAR(100),

    email VARCHAR(320)
        NOT NULL,

    phone_number VARCHAR(32),

    status identity.customer_status
        NOT NULL
        DEFAULT 'PENDING',

    registered_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    last_login_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    deleted_at TIMESTAMPTZ,

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_customers
        PRIMARY KEY (customer_id),

    CONSTRAINT uq_customers_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_customers_email
        UNIQUE (email),

    CONSTRAINT ck_customers_first_name_not_blank
        CHECK (char_length(btrim(first_name)) > 0),

    CONSTRAINT ck_customers_last_name_not_blank
        CHECK (
            last_name IS NULL
            OR char_length(btrim(last_name)) > 0
        ),

    CONSTRAINT ck_customers_email_normalized
        CHECK (
            email = lower(btrim(email))
            AND char_length(email) >= 3
        ),

    CONSTRAINT ck_customers_phone_not_blank
        CHECK (
            phone_number IS NULL
            OR char_length(btrim(phone_number)) > 0
        ),

    CONSTRAINT ck_customers_version_nonnegative
        CHECK (version >= 0),

    CONSTRAINT ck_customers_deleted_after_creation
        CHECK (
            deleted_at IS NULL
            OR deleted_at >= created_at
        )
);

COMMENT ON TABLE identity.customers IS
    'Customer business profiles. Authentication secrets are stored separately.';

COMMENT ON COLUMN identity.customers.customer_id IS
    'Internal high-performance identifier used for joins.';

COMMENT ON COLUMN identity.customers.public_id IS
    'Public UUID exposed through APIs and events.';

COMMENT ON COLUMN identity.customers.email IS
    'Lowercase and trimmed customer email address.';

COMMENT ON COLUMN identity.customers.version IS
    'Optimistic-locking version managed by the application.';

CREATE INDEX idx_customers_status_registered
    ON identity.customers (
        status,
        registered_at DESC
    )
    WHERE deleted_at IS NULL;

CREATE INDEX idx_customers_registered_at
    ON identity.customers (
        registered_at DESC
    );

/*
The UNIQUE constraint on email already creates an index.
Do not create a duplicate email index.
*/

/*
=========================================================
CREDENTIALS
=========================================================
*/

CREATE TABLE identity.credentials (
    credential_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    customer_id BIGINT
        NOT NULL,

    password_hash VARCHAR(255)
        NOT NULL,

    password_changed_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    failed_attempts SMALLINT
        NOT NULL
        DEFAULT 0,

    locked_until TIMESTAMPTZ,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    CONSTRAINT pk_credentials
        PRIMARY KEY (credential_id),

    CONSTRAINT uq_credentials_customer_id
        UNIQUE (customer_id),

    CONSTRAINT fk_credentials_customer
        FOREIGN KEY (customer_id)
        REFERENCES identity.customers (customer_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT ck_credentials_password_hash_not_blank
        CHECK (char_length(btrim(password_hash)) >= 20),

    CONSTRAINT ck_credentials_failed_attempts
        CHECK (failed_attempts >= 0),

    CONSTRAINT ck_credentials_locked_until
        CHECK (
            locked_until IS NULL
            OR locked_until >= created_at
        )
);

COMMENT ON TABLE identity.credentials IS
    'Customer authentication hashes and lockout state. Plain-text passwords are prohibited.';

COMMENT ON COLUMN identity.credentials.password_hash IS
    'One-way password hash created by the authentication service.';

/*
The UNIQUE constraint on customer_id creates the required
one-to-one lookup index automatically.
*/

/*
=========================================================
ADDRESSES
=========================================================
*/

CREATE TABLE identity.addresses (
    address_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    customer_id BIGINT
        NOT NULL,

    address_type identity.address_type
        NOT NULL
        DEFAULT 'HOME',

    recipient_name VARCHAR(200)
        NOT NULL,

    phone_number VARCHAR(32),

    address_line_1 VARCHAR(255)
        NOT NULL,

    address_line_2 VARCHAR(255),

    city VARCHAR(100)
        NOT NULL,

    state_region VARCHAR(100)
        NOT NULL,

    postal_code VARCHAR(20)
        NOT NULL,

    country_code CHAR(2)
        NOT NULL,

    is_default BOOLEAN
        NOT NULL
        DEFAULT FALSE,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    deleted_at TIMESTAMPTZ,

    CONSTRAINT pk_addresses
        PRIMARY KEY (address_id),

    CONSTRAINT uq_addresses_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_addresses_customer
        FOREIGN KEY (customer_id)
        REFERENCES identity.customers (customer_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT ck_addresses_recipient_not_blank
        CHECK (char_length(btrim(recipient_name)) > 0),

    CONSTRAINT ck_addresses_line_1_not_blank
        CHECK (char_length(btrim(address_line_1)) > 0),

    CONSTRAINT ck_addresses_city_not_blank
        CHECK (char_length(btrim(city)) > 0),

    CONSTRAINT ck_addresses_state_not_blank
        CHECK (char_length(btrim(state_region)) > 0),

    CONSTRAINT ck_addresses_postal_code_not_blank
        CHECK (char_length(btrim(postal_code)) > 0),

    CONSTRAINT ck_addresses_country_code
        CHECK (
            country_code = upper(country_code)
            AND country_code ~ '^[A-Z]{2}$'
        ),

    CONSTRAINT ck_addresses_phone_not_blank
        CHECK (
            phone_number IS NULL
            OR char_length(btrim(phone_number)) > 0
        ),

    CONSTRAINT ck_addresses_deleted_after_creation
        CHECK (
            deleted_at IS NULL
            OR deleted_at >= created_at
        )
);

COMMENT ON TABLE identity.addresses IS
    'Reusable customer addresses. Orders will store independent address snapshots.';

CREATE INDEX idx_addresses_customer
    ON identity.addresses (
        customer_id,
        created_at DESC
    )
    WHERE deleted_at IS NULL;

CREATE INDEX idx_addresses_postal_code
    ON identity.addresses (postal_code)
    WHERE deleted_at IS NULL;

/*
Only one undeleted default address of each type is allowed
for a customer.
*/

CREATE UNIQUE INDEX uq_addresses_customer_default_type
    ON identity.addresses (
        customer_id,
        address_type
    )
    WHERE is_default = TRUE
      AND deleted_at IS NULL;