/*
=========================================================
Retail Intelligence Platform
Migration: V004
Purpose: Create the Catalogue domain
=========================================================
*/

SET ROLE retail_owner;

/*
=========================================================
BRANDS
=========================================================
*/

CREATE TABLE catalog.brands (
    brand_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    brand_name VARCHAR(150)
        NOT NULL,

    description TEXT,

    website_url TEXT,

    is_active BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    deleted_at TIMESTAMPTZ,

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_brands
        PRIMARY KEY (brand_id),

    CONSTRAINT uq_brands_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_brands_name
        UNIQUE (brand_name),

    CONSTRAINT ck_brands_name_not_blank
        CHECK (char_length(btrim(brand_name)) > 0),

    CONSTRAINT ck_brands_website_not_blank
        CHECK (
            website_url IS NULL
            OR char_length(btrim(website_url)) > 0
        ),

    CONSTRAINT ck_brands_version_nonnegative
        CHECK (version >= 0),

    CONSTRAINT ck_brands_deleted_after_creation
        CHECK (
            deleted_at IS NULL
            OR deleted_at >= created_at
        )
);

COMMENT ON TABLE catalog.brands IS
    'Product-brand master data. Brands are deactivated instead of ordinarily deleted.';

CREATE INDEX idx_brands_active_name
    ON catalog.brands (brand_name)
    WHERE is_active = TRUE
      AND deleted_at IS NULL;

/*
=========================================================
CATEGORIES
=========================================================
*/

CREATE TABLE catalog.categories (
    category_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    parent_category_id BIGINT,

    category_name VARCHAR(150)
        NOT NULL,

    category_slug VARCHAR(180)
        NOT NULL,

    description TEXT,

    display_order INTEGER
        NOT NULL
        DEFAULT 0,

    is_active BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    deleted_at TIMESTAMPTZ,

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_categories
        PRIMARY KEY (category_id),

    CONSTRAINT uq_categories_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_categories_slug
        UNIQUE (category_slug),

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_category_id)
        REFERENCES catalog.categories (category_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,

    CONSTRAINT ck_categories_name_not_blank
        CHECK (char_length(btrim(category_name)) > 0),

    CONSTRAINT ck_categories_slug_normalized
        CHECK (
            category_slug = lower(btrim(category_slug))
            AND category_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
        ),

    CONSTRAINT ck_categories_display_order
        CHECK (display_order >= 0),

    CONSTRAINT ck_categories_not_own_parent
        CHECK (
            parent_category_id IS NULL
            OR parent_category_id <> category_id
        ),

    CONSTRAINT ck_categories_version_nonnegative
        CHECK (version >= 0),

    CONSTRAINT ck_categories_deleted_after_creation
        CHECK (
            deleted_at IS NULL
            OR deleted_at >= created_at
        )
);

COMMENT ON TABLE catalog.categories IS
    'Hierarchical catalogue categories using a parent-category relationship.';

CREATE INDEX idx_categories_parent
    ON catalog.categories (
        parent_category_id,
        display_order,
        category_name
    )
    WHERE deleted_at IS NULL;

CREATE INDEX idx_categories_active_order
    ON catalog.categories (
        display_order,
        category_name
    )
    WHERE is_active = TRUE
      AND deleted_at IS NULL;

/*
=========================================================
PRODUCTS
=========================================================
*/

CREATE TABLE catalog.products (
    product_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    sku VARCHAR(64)
        NOT NULL,

    category_id BIGINT
        NOT NULL,

    brand_id BIGINT,

    product_name VARCHAR(255)
        NOT NULL,

    product_slug VARCHAR(280)
        NOT NULL,

    short_description VARCHAR(1000),

    full_description TEXT,

    status catalog.product_status
        NOT NULL
        DEFAULT 'DRAFT',

    attributes JSONB
        NOT NULL
        DEFAULT '{}'::JSONB,

    weight_grams INTEGER,

    search_document TSVECTOR
        GENERATED ALWAYS AS (
            to_tsvector(
                'simple',
                coalesce(product_name, '')
                || ' '
                || coalesce(short_description, '')
                || ' '
                || coalesce(full_description, '')
            )
        ) STORED,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    deleted_at TIMESTAMPTZ,

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_products
        PRIMARY KEY (product_id),

    CONSTRAINT uq_products_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_products_sku
        UNIQUE (sku),

    CONSTRAINT uq_products_slug
        UNIQUE (product_slug),

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES catalog.categories (category_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id)
        REFERENCES catalog.brands (brand_id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,

    CONSTRAINT ck_products_sku_normalized
        CHECK (
            sku = upper(btrim(sku))
            AND char_length(sku) > 0
        ),

    CONSTRAINT ck_products_name_not_blank
        CHECK (char_length(btrim(product_name)) > 0),

    CONSTRAINT ck_products_slug_normalized
        CHECK (
            product_slug = lower(btrim(product_slug))
            AND product_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
        ),

    CONSTRAINT ck_products_attributes_object
        CHECK (jsonb_typeof(attributes) = 'object'),

    CONSTRAINT ck_products_weight_positive
        CHECK (
            weight_grams IS NULL
            OR weight_grams > 0
        ),

    CONSTRAINT ck_products_version_nonnegative
        CHECK (version >= 0),

    CONSTRAINT ck_products_deleted_after_creation
        CHECK (
            deleted_at IS NULL
            OR deleted_at >= created_at
        )
);

COMMENT ON TABLE catalog.products IS
    'Product master data, including flexible JSONB attributes and generated search content.';

COMMENT ON COLUMN catalog.products.attributes IS
    'Category-specific attributes such as colour, storage size or material.';

COMMENT ON COLUMN catalog.products.search_document IS
    'Generated full-text search vector derived from product descriptions.';

CREATE INDEX idx_products_category_status
    ON catalog.products (
        category_id,
        status,
        product_name
    )
    WHERE deleted_at IS NULL;

CREATE INDEX idx_products_brand
    ON catalog.products (
        brand_id,
        product_name
    )
    WHERE brand_id IS NOT NULL
      AND deleted_at IS NULL;

CREATE INDEX idx_products_active_created
    ON catalog.products (
        created_at DESC
    )
    WHERE status = 'ACTIVE'
      AND deleted_at IS NULL;

CREATE INDEX idx_products_attributes_gin
    ON catalog.products
    USING GIN (attributes);

CREATE INDEX idx_products_search_gin
    ON catalog.products
    USING GIN (search_document);

/*
=========================================================
PRODUCT PRICES
=========================================================
*/

CREATE TABLE catalog.product_prices (
    product_price_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    product_id BIGINT
        NOT NULL,

    currency_code CHAR(3)
        NOT NULL,

    list_price NUMERIC(19,4)
        NOT NULL,

    sale_price NUMERIC(19,4),

    valid_from TIMESTAMPTZ
        NOT NULL,

    valid_to TIMESTAMPTZ,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    created_by VARCHAR(100),

    CONSTRAINT pk_product_prices
        PRIMARY KEY (product_price_id),

    CONSTRAINT fk_product_prices_product
        FOREIGN KEY (product_id)
        REFERENCES catalog.products (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_product_prices_start
        UNIQUE (
            product_id,
            currency_code,
            valid_from
        ),

    CONSTRAINT ck_product_prices_currency
        CHECK (
            currency_code = upper(currency_code)
            AND currency_code ~ '^[A-Z]{3}$'
        ),

    CONSTRAINT ck_product_prices_list_nonnegative
        CHECK (list_price >= 0),

    CONSTRAINT ck_product_prices_sale_nonnegative
        CHECK (
            sale_price IS NULL
            OR sale_price >= 0
        ),

    CONSTRAINT ck_product_prices_sale_not_above_list
        CHECK (
            sale_price IS NULL
            OR sale_price <= list_price
        ),

    CONSTRAINT ck_product_prices_valid_period
        CHECK (
            valid_to IS NULL
            OR valid_to > valid_from
        ),

    CONSTRAINT ck_product_prices_created_by
        CHECK (
            created_by IS NULL
            OR char_length(btrim(created_by)) > 0
        )
);

COMMENT ON TABLE catalog.product_prices IS
    'Effective-dated product-price history. Past prices are preserved.';

/*
One product can have only one open-ended current price
for each currency.
*/

CREATE UNIQUE INDEX uq_product_prices_current
    ON catalog.product_prices (
        product_id,
        currency_code
    )
    WHERE valid_to IS NULL;

CREATE INDEX idx_product_prices_effective_lookup
    ON catalog.product_prices (
        product_id,
        currency_code,
        valid_from DESC,
        valid_to
    );

/*
Supports price-change analysis by time.
*/

CREATE INDEX idx_product_prices_created
    ON catalog.product_prices (
        created_at DESC
    );

RESET ROLE;