/*
=========================================================
Retail Intelligence Platform
Migration: V005
Purpose:
  - Create warehouses
  - Create product stock
  - Prevent invalid inventory quantities
  - Support pessimistic and optimistic concurrency control
=========================================================
*/

SET ROLE retail_owner;

/*
=========================================================
WAREHOUSES
=========================================================
*/

CREATE TABLE inventory.warehouses (
    warehouse_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    warehouse_code VARCHAR(32)
        NOT NULL,

    warehouse_name VARCHAR(150)
        NOT NULL,

    address_line_1 VARCHAR(255)
        NOT NULL,

    address_line_2 VARCHAR(255),

    city VARCHAR(100)
        NOT NULL,

    state_region VARCHAR(100)
        NOT NULL,

    postal_code VARCHAR(20)
        NOT NULL,

    country_code CHAR(2)
        NOT NULL,

    is_active BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    deleted_at TIMESTAMPTZ,

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_warehouses
        PRIMARY KEY (warehouse_id),

    CONSTRAINT uq_warehouses_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_warehouses_code
        UNIQUE (warehouse_code),

    CONSTRAINT ck_warehouses_code_normalized
        CHECK (
            warehouse_code = upper(btrim(warehouse_code))
            AND warehouse_code ~ '^[A-Z0-9][A-Z0-9_-]{1,31}$'
        ),

    CONSTRAINT ck_warehouses_name_not_blank
        CHECK (char_length(btrim(warehouse_name)) > 0),

    CONSTRAINT ck_warehouses_address_not_blank
        CHECK (char_length(btrim(address_line_1)) > 0),

    CONSTRAINT ck_warehouses_city_not_blank
        CHECK (char_length(btrim(city)) > 0),

    CONSTRAINT ck_warehouses_state_not_blank
        CHECK (char_length(btrim(state_region)) > 0),

    CONSTRAINT ck_warehouses_postal_code_not_blank
        CHECK (char_length(btrim(postal_code)) > 0),

    CONSTRAINT ck_warehouses_country_code
        CHECK (
            country_code = upper(country_code)
            AND country_code ~ '^[A-Z]{2}$'
        ),

    CONSTRAINT ck_warehouses_version_nonnegative
        CHECK (version >= 0),

    CONSTRAINT ck_warehouses_deleted_after_creation
        CHECK (
            deleted_at IS NULL
            OR deleted_at >= created_at
        )
);

COMMENT ON TABLE inventory.warehouses IS
    'Physical or logical fulfilment locations holding product inventory.';

CREATE INDEX idx_warehouses_active_location
    ON inventory.warehouses (
        country_code,
        state_region,
        city,
        warehouse_name
    )
    WHERE is_active = TRUE
      AND deleted_at IS NULL;

/*
=========================================================
STOCK
=========================================================
*/

CREATE TABLE inventory.stock (
    stock_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    warehouse_id BIGINT
        NOT NULL,

    product_id BIGINT
        NOT NULL,

    on_hand_quantity INTEGER
        NOT NULL
        DEFAULT 0,

    reserved_quantity INTEGER
        NOT NULL
        DEFAULT 0,

    available_quantity INTEGER
        GENERATED ALWAYS AS (
            on_hand_quantity - reserved_quantity
        ) STORED,

    reorder_level INTEGER
        NOT NULL
        DEFAULT 0,

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_stock
        PRIMARY KEY (stock_id),

    CONSTRAINT fk_stock_warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES inventory.warehouses (warehouse_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_stock_product
        FOREIGN KEY (product_id)
        REFERENCES catalog.products (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_stock_warehouse_product
        UNIQUE (warehouse_id, product_id),

    CONSTRAINT ck_stock_on_hand_nonnegative
        CHECK (on_hand_quantity >= 0),

    CONSTRAINT ck_stock_reserved_nonnegative
        CHECK (reserved_quantity >= 0),

    CONSTRAINT ck_stock_reserved_not_above_on_hand
        CHECK (reserved_quantity <= on_hand_quantity),

    CONSTRAINT ck_stock_reorder_level_nonnegative
        CHECK (reorder_level >= 0),

    CONSTRAINT ck_stock_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE inventory.stock IS
    'Current product quantities per warehouse. Available quantity equals on-hand minus reserved.';

COMMENT ON COLUMN inventory.stock.on_hand_quantity IS
    'Physical quantity currently held by the warehouse.';

COMMENT ON COLUMN inventory.stock.reserved_quantity IS
    'Quantity reserved for orders but not yet consumed.';

COMMENT ON COLUMN inventory.stock.available_quantity IS
    'Generated quantity available for new reservations.';

COMMENT ON COLUMN inventory.stock.version IS
    'Optimistic-lock version incremented by every successful stock mutation.';

CREATE INDEX idx_stock_product
    ON inventory.stock (
        product_id,
        warehouse_id
    );

CREATE INDEX idx_stock_available
    ON inventory.stock (
        product_id,
        available_quantity DESC
    )
    WHERE available_quantity > 0;

CREATE INDEX idx_stock_reorder_required
    ON inventory.stock (
        warehouse_id,
        available_quantity
    )
    WHERE available_quantity <= reorder_level;

RESET ROLE;