/*
=========================================================
Retail Intelligence Platform
Migration: V006
Purpose:
  - Create customer shopping carts
  - Create cart line items
  - Enforce one active cart per customer and currency
  - Preserve displayed-price snapshots
=========================================================
*/

SET ROLE retail_owner;

/*
=========================================================
CARTS
=========================================================
*/

CREATE TABLE commerce.carts (
    cart_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    customer_id BIGINT
        NOT NULL,

    status commerce.cart_status
        NOT NULL
        DEFAULT 'ACTIVE',

    currency_code CHAR(3)
        NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    expires_at TIMESTAMPTZ,

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_carts
        PRIMARY KEY (cart_id),

    CONSTRAINT uq_carts_public_id
        UNIQUE (public_id),

    CONSTRAINT fk_carts_customer
        FOREIGN KEY (customer_id)
        REFERENCES identity.customers (customer_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_carts_currency
        CHECK (
            currency_code = upper(currency_code)
            AND currency_code ~ '^[A-Z]{3}$'
        ),

    CONSTRAINT ck_carts_expiration
        CHECK (
            expires_at IS NULL
            OR expires_at > created_at
        ),

    CONSTRAINT ck_carts_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE commerce.carts IS
    'Customer shopping carts. Active carts may expire or become checked out.';

COMMENT ON COLUMN commerce.carts.version IS
    'Optimistic-lock version incremented whenever the cart changes.';

/*
A customer may have one active cart per currency.

The currency dimension allows separate carts such as INR and SGD
without mixing monetary values.
*/

CREATE UNIQUE INDEX uq_carts_active_customer_currency
    ON commerce.carts (
        customer_id,
        currency_code
    )
    WHERE status = 'ACTIVE';

CREATE INDEX idx_carts_customer_status
    ON commerce.carts (
        customer_id,
        status,
        updated_at DESC
    );

CREATE INDEX idx_carts_active_expiration
    ON commerce.carts (
        expires_at
    )
    WHERE status = 'ACTIVE'
      AND expires_at IS NOT NULL;

/*
=========================================================
CART ITEMS
=========================================================
*/

CREATE TABLE commerce.cart_items (
    cart_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    cart_id BIGINT
        NOT NULL,

    product_id BIGINT
        NOT NULL,

    quantity INTEGER
        NOT NULL,

    displayed_unit_price NUMERIC(19,4)
        NOT NULL,

    added_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_cart_items
        PRIMARY KEY (cart_item_id),

    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES commerce.carts (cart_id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id)
        REFERENCES catalog.products (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_cart_items_cart_product
        UNIQUE (cart_id, product_id),

    CONSTRAINT ck_cart_items_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT ck_cart_items_price_nonnegative
        CHECK (displayed_unit_price >= 0),

    CONSTRAINT ck_cart_items_updated_after_added
        CHECK (updated_at >= added_at),

    CONSTRAINT ck_cart_items_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE commerce.cart_items IS
    'Products and requested quantities currently held in a shopping cart.';

COMMENT ON COLUMN commerce.cart_items.displayed_unit_price IS
    'Price shown when the item was added or last repriced; checkout must revalidate it.';

CREATE INDEX idx_cart_items_product
    ON commerce.cart_items (
        product_id,
        cart_id
    );

RESET ROLE;