/*
=========================================================
Retail Intelligence Platform
Migration: V007
Purpose:
  - Create orders and immutable order-item snapshots
  - Preserve billing and shipping address snapshots
  - Record order-status history
  - Enforce idempotent checkout
  - Enforce monetary consistency
=========================================================
*/

SET ROLE retail_owner;

/*
=========================================================
ORDERS
=========================================================
*/

CREATE TABLE commerce.orders (
    order_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    order_number VARCHAR(40)
        NOT NULL,

    customer_id BIGINT
        NOT NULL,

    cart_id BIGINT,

    status commerce.order_status
        NOT NULL
        DEFAULT 'PENDING',

    currency_code CHAR(3)
        NOT NULL,

    subtotal_amount NUMERIC(19,4)
        NOT NULL,

    discount_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    tax_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    shipping_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    total_amount NUMERIC(19,4)
        NOT NULL,

    idempotency_key VARCHAR(100)
        NOT NULL,

    ordered_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_orders
        PRIMARY KEY (order_id),

    CONSTRAINT uq_orders_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_orders_number
        UNIQUE (order_number),

    CONSTRAINT uq_orders_idempotency
        UNIQUE (idempotency_key),

    CONSTRAINT uq_orders_cart
        UNIQUE (cart_id),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES identity.customers (customer_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_orders_cart
        FOREIGN KEY (cart_id)
        REFERENCES commerce.carts (cart_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_orders_number_normalized
        CHECK (
            order_number = upper(btrim(order_number))
            AND order_number ~ '^[A-Z0-9][A-Z0-9_-]{2,39}$'
        ),

    CONSTRAINT ck_orders_currency
        CHECK (
            currency_code = upper(currency_code)
            AND currency_code ~ '^[A-Z]{3}$'
        ),

    CONSTRAINT ck_orders_subtotal_nonnegative
        CHECK (subtotal_amount >= 0),

    CONSTRAINT ck_orders_discount_nonnegative
        CHECK (discount_amount >= 0),

    CONSTRAINT ck_orders_discount_not_above_subtotal
        CHECK (discount_amount <= subtotal_amount),

    CONSTRAINT ck_orders_tax_nonnegative
        CHECK (tax_amount >= 0),

    CONSTRAINT ck_orders_shipping_nonnegative
        CHECK (shipping_amount >= 0),

    CONSTRAINT ck_orders_total_nonnegative
        CHECK (total_amount >= 0),

    CONSTRAINT ck_orders_total_consistent
        CHECK (
            total_amount =
                subtotal_amount
                - discount_amount
                + tax_amount
                + shipping_amount
        ),

    CONSTRAINT ck_orders_idempotency_not_blank
        CHECK (char_length(btrim(idempotency_key)) > 0),

    CONSTRAINT ck_orders_updated_after_creation
        CHECK (updated_at >= created_at),

    CONSTRAINT ck_orders_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE commerce.orders IS
    'Customer orders created through idempotent checkout. Monetary values use the order currency.';

COMMENT ON COLUMN commerce.orders.idempotency_key IS
    'Client-generated retry key ensuring repeated checkout requests return the same order.';

CREATE INDEX idx_orders_customer_time
    ON commerce.orders (
        customer_id,
        ordered_at DESC
    );

CREATE INDEX idx_orders_status_time
    ON commerce.orders (
        status,
        ordered_at
    );

/*
=========================================================
ORDER ITEMS
=========================================================
*/

CREATE TABLE commerce.order_items (
    order_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    order_id BIGINT
        NOT NULL,

    product_id BIGINT
        NOT NULL,

    sku_snapshot VARCHAR(64)
        NOT NULL,

    product_name_snapshot VARCHAR(255)
        NOT NULL,

    quantity INTEGER
        NOT NULL,

    unit_price NUMERIC(19,4)
        NOT NULL,

    discount_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    tax_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    line_total NUMERIC(19,4)
        NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    CONSTRAINT pk_order_items
        PRIMARY KEY (order_item_id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES commerce.orders (order_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES catalog.products (product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_items_order_product
        UNIQUE (order_id, product_id),

    CONSTRAINT ck_order_items_sku_not_blank
        CHECK (char_length(btrim(sku_snapshot)) > 0),

    CONSTRAINT ck_order_items_name_not_blank
        CHECK (char_length(btrim(product_name_snapshot)) > 0),

    CONSTRAINT ck_order_items_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT ck_order_items_unit_price_nonnegative
        CHECK (unit_price >= 0),

    CONSTRAINT ck_order_items_discount_nonnegative
        CHECK (discount_amount >= 0),

    CONSTRAINT ck_order_items_discount_limit
        CHECK (discount_amount <= quantity * unit_price),

    CONSTRAINT ck_order_items_tax_nonnegative
        CHECK (tax_amount >= 0),

    CONSTRAINT ck_order_items_total_nonnegative
        CHECK (line_total >= 0),

    CONSTRAINT ck_order_items_total_consistent
        CHECK (
            line_total =
                quantity * unit_price
                - discount_amount
                + tax_amount
        )
);

COMMENT ON TABLE commerce.order_items IS
    'Immutable product, quantity and price snapshots belonging to an order.';

CREATE INDEX idx_order_items_order
    ON commerce.order_items (order_id);

CREATE INDEX idx_order_items_product
    ON commerce.order_items (
        product_id,
        order_id
    );

/*
=========================================================
ORDER ADDRESS SNAPSHOTS
=========================================================
*/

CREATE TABLE commerce.order_addresses (
    order_address_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    order_id BIGINT
        NOT NULL,

    address_role VARCHAR(20)
        NOT NULL,

    recipient_name VARCHAR(200)
        NOT NULL,

    phone_number VARCHAR(32),

    address_line_1 VARCHAR(255)
        NOT NULL,

    address_line_2 VARCHAR(255),

    city VARCHAR(100)
        NOT NULL,

    state_region VARCHAR(100)
        NOT NULL,

    postal_code VARCHAR(20)
        NOT NULL,

    country_code CHAR(2)
        NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    CONSTRAINT pk_order_addresses
        PRIMARY KEY (order_address_id),

    CONSTRAINT fk_order_addresses_order
        FOREIGN KEY (order_id)
        REFERENCES commerce.orders (order_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_addresses_role
        UNIQUE (order_id, address_role),

    CONSTRAINT ck_order_addresses_role
        CHECK (address_role IN ('BILLING', 'SHIPPING')),

    CONSTRAINT ck_order_addresses_recipient
        CHECK (char_length(btrim(recipient_name)) > 0),

    CONSTRAINT ck_order_addresses_phone
        CHECK (
            phone_number IS NULL
            OR char_length(btrim(phone_number)) > 0
        ),

    CONSTRAINT ck_order_addresses_line_1
        CHECK (char_length(btrim(address_line_1)) > 0),

    CONSTRAINT ck_order_addresses_city
        CHECK (char_length(btrim(city)) > 0),

    CONSTRAINT ck_order_addresses_state
        CHECK (char_length(btrim(state_region)) > 0),

    CONSTRAINT ck_order_addresses_postal
        CHECK (char_length(btrim(postal_code)) > 0),

    CONSTRAINT ck_order_addresses_country
        CHECK (
            country_code = upper(country_code)
            AND country_code ~ '^[A-Z]{2}$'
        )
);

COMMENT ON TABLE commerce.order_addresses IS
    'Immutable billing and shipping snapshots retained independently of customer address changes.';

/*
=========================================================
ORDER STATUS HISTORY
=========================================================
*/

CREATE TABLE commerce.order_status_history (
    order_status_history_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    order_id BIGINT
        NOT NULL,

    previous_status commerce.order_status,

    new_status commerce.order_status
        NOT NULL,

    reason VARCHAR(500),

    changed_by VARCHAR(100),

    changed_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    CONSTRAINT pk_order_status_history
        PRIMARY KEY (order_status_history_id),

    CONSTRAINT fk_order_status_history_order
        FOREIGN KEY (order_id)
        REFERENCES commerce.orders (order_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_order_status_history_change
        CHECK (
            previous_status IS NULL
            OR previous_status <> new_status
        ),

    CONSTRAINT ck_order_status_history_reason
        CHECK (
            reason IS NULL
            OR char_length(btrim(reason)) > 0
        ),

    CONSTRAINT ck_order_status_history_actor
        CHECK (
            changed_by IS NULL
            OR char_length(btrim(changed_by)) > 0
        )
);

COMMENT ON TABLE commerce.order_status_history IS
    'Append-only audit history of order lifecycle transitions.';

CREATE INDEX idx_order_status_history
    ON commerce.order_status_history (
        order_id,
        changed_at
    );

RESET ROLE;