/*
=========================================================
Retail Intelligence Platform
Migration: V008
Purpose:
  - Create order inventory reservations
  - Enforce order-item and product consistency
  - Enforce warehouse stock consistency
  - Support reservation expiry and release processing
=========================================================
*/

SET ROLE retail_owner;

/*
This composite key allows reservations to prove that the supplied
order_id and product_id belong to the specified order_item_id.

It is intentionally introduced in V008 rather than editing the
already-applied V007 migration.
*/

ALTER TABLE commerce.order_items
    ADD CONSTRAINT uq_order_items_identity
    UNIQUE (
        order_item_id,
        order_id,
        product_id
    );

/*
=========================================================
INVENTORY RESERVATIONS
=========================================================
*/

CREATE TABLE inventory.reservations (
    reservation_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    order_id BIGINT
        NOT NULL,

    order_item_id BIGINT
        NOT NULL,

    warehouse_id BIGINT
        NOT NULL,

    product_id BIGINT
        NOT NULL,

    quantity INTEGER
        NOT NULL,

    status inventory.reservation_status
        NOT NULL
        DEFAULT 'PENDING',

    expires_at TIMESTAMPTZ
        NOT NULL,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_reservations
        PRIMARY KEY (reservation_id),

    CONSTRAINT uq_reservations_public_id
        UNIQUE (public_id),

    /*
    One reservation record per order item and warehouse.

    This permits one order item to be split across multiple
    warehouses but prevents retry-created duplicates.
    */
    CONSTRAINT uq_reservations_item_warehouse
        UNIQUE (
            order_item_id,
            warehouse_id
        ),

    /*
    Ensures all three values describe the same order item:
      - order_item_id
      - order_id
      - product_id
    */
    CONSTRAINT fk_reservations_order_item_identity
        FOREIGN KEY (
            order_item_id,
            order_id,
            product_id
        )
        REFERENCES commerce.order_items (
            order_item_id,
            order_id,
            product_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    /*
    Ensures the selected warehouse actually has a stock record
    for the selected product.
    */
    CONSTRAINT fk_reservations_stock
        FOREIGN KEY (
            warehouse_id,
            product_id
        )
        REFERENCES inventory.stock (
            warehouse_id,
            product_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_reservations_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT ck_reservations_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT ck_reservations_updated_after_creation
        CHECK (updated_at >= created_at),

    CONSTRAINT ck_reservations_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE inventory.reservations IS
    'Time-limited inventory allocations associated with order items.';

COMMENT ON COLUMN inventory.reservations.expires_at IS
    'Deadline after which an unconsumed reservation may be released.';

COMMENT ON COLUMN inventory.reservations.version IS
    'Optimistic-lock version incremented on each reservation transition.';

CREATE INDEX idx_reservations_order
    ON inventory.reservations (
        order_id,
        order_item_id
    );

CREATE INDEX idx_reservations_stock_status
    ON inventory.reservations (
        warehouse_id,
        product_id,
        status
    );

CREATE INDEX idx_reservations_expiry
    ON inventory.reservations (
        expires_at,
        reservation_id
    )
    WHERE status IN ('PENDING', 'RESERVED');

RESET ROLE;