/*
=========================================================
Retail Intelligence Platform
Migration: V009
Purpose:
  - Create payments
  - Record provider payment attempts
  - Record payment-status history
  - Enforce payment idempotency and monetary consistency
=========================================================
*/

SET ROLE retail_owner;

/*
=========================================================
PAYMENTS
=========================================================
*/

CREATE TABLE payment.payments (
    payment_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    public_id UUID
        NOT NULL
        DEFAULT gen_random_uuid(),

    order_id BIGINT
        NOT NULL,

    status payment.payment_status
        NOT NULL
        DEFAULT 'INITIATED',

    currency_code CHAR(3)
        NOT NULL,

    requested_amount NUMERIC(19,4)
        NOT NULL,

    paid_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    refunded_amount NUMERIC(19,4)
        NOT NULL
        DEFAULT 0,

    payment_method VARCHAR(30)
        NOT NULL,

    provider_name VARCHAR(100),

    provider_payment_reference VARCHAR(255),

    idempotency_key VARCHAR(100)
        NOT NULL,

    initiated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    version BIGINT
        NOT NULL
        DEFAULT 0,

    CONSTRAINT pk_payments
        PRIMARY KEY (payment_id),

    CONSTRAINT uq_payments_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_payments_idempotency
        UNIQUE (idempotency_key),

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES commerce.orders (order_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_payments_currency
        CHECK (
            currency_code = upper(currency_code)
            AND currency_code ~ '^[A-Z]{3}$'
        ),

    CONSTRAINT ck_payments_requested_positive
        CHECK (requested_amount > 0),

    CONSTRAINT ck_payments_paid_nonnegative
        CHECK (paid_amount >= 0),

    CONSTRAINT ck_payments_paid_not_above_requested
        CHECK (paid_amount <= requested_amount),

    CONSTRAINT ck_payments_refunded_nonnegative
        CHECK (refunded_amount >= 0),

    CONSTRAINT ck_payments_refunded_not_above_paid
        CHECK (refunded_amount <= paid_amount),

    CONSTRAINT ck_payments_method_not_blank
        CHECK (char_length(btrim(payment_method)) > 0),

    CONSTRAINT ck_payments_provider_name
        CHECK (
            provider_name IS NULL
            OR char_length(btrim(provider_name)) > 0
        ),

    CONSTRAINT ck_payments_provider_reference
        CHECK (
            provider_payment_reference IS NULL
            OR char_length(btrim(provider_payment_reference)) > 0
        ),

    CONSTRAINT ck_payments_idempotency_not_blank
        CHECK (char_length(btrim(idempotency_key)) > 0),

    CONSTRAINT ck_payments_completion_time
        CHECK (
            completed_at IS NULL
            OR completed_at >= initiated_at
        ),

    CONSTRAINT ck_payments_updated_after_creation
        CHECK (updated_at >= created_at),

    CONSTRAINT ck_payments_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE payment.payments IS
    'Logical payment records associated with orders. One payment may have multiple provider attempts.';

COMMENT ON COLUMN payment.payments.idempotency_key IS
    'Client or service retry key preventing duplicate logical payments.';

COMMENT ON COLUMN payment.payments.provider_payment_reference IS
    'Payment identifier returned by the external payment provider.';

/*
Multiple NULL provider references are allowed, but every populated
provider/reference pair must be unique.
*/

CREATE UNIQUE INDEX uq_payments_provider_reference
    ON payment.payments (
        provider_name,
        provider_payment_reference
    )
    WHERE provider_payment_reference IS NOT NULL;

CREATE INDEX idx_payments_order
    ON payment.payments (
        order_id,
        initiated_at DESC
    );

CREATE INDEX idx_payments_status_time
    ON payment.payments (
        status,
        initiated_at
    );

/*
=========================================================
PAYMENT ATTEMPTS
=========================================================
*/

CREATE TABLE payment.payment_attempts (
    payment_attempt_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    payment_id BIGINT
        NOT NULL,

    attempt_number SMALLINT
        NOT NULL,

    status payment.payment_status
        NOT NULL,

    provider_request_id VARCHAR(255),

    provider_response_code VARCHAR(100),

    failure_reason VARCHAR(500),

    requested_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    responded_at TIMESTAMPTZ,

    CONSTRAINT pk_payment_attempts
        PRIMARY KEY (payment_attempt_id),

    CONSTRAINT fk_payment_attempts_payment
        FOREIGN KEY (payment_id)
        REFERENCES payment.payments (payment_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_payment_attempt_number
        UNIQUE (
            payment_id,
            attempt_number
        ),

    CONSTRAINT ck_payment_attempt_number_positive
        CHECK (attempt_number > 0),

    CONSTRAINT ck_payment_attempt_request_id
        CHECK (
            provider_request_id IS NULL
            OR char_length(btrim(provider_request_id)) > 0
        ),

    CONSTRAINT ck_payment_attempt_response_code
        CHECK (
            provider_response_code IS NULL
            OR char_length(btrim(provider_response_code)) > 0
        ),

    CONSTRAINT ck_payment_attempt_failure_reason
        CHECK (
            failure_reason IS NULL
            OR char_length(btrim(failure_reason)) > 0
        ),

    CONSTRAINT ck_payment_attempt_response_time
        CHECK (
            responded_at IS NULL
            OR responded_at >= requested_at
        )
);

COMMENT ON TABLE payment.payment_attempts IS
    'Individual requests made to payment providers for a logical payment.';

CREATE UNIQUE INDEX uq_payment_attempt_provider_request
    ON payment.payment_attempts (provider_request_id)
    WHERE provider_request_id IS NOT NULL;

CREATE INDEX idx_payment_attempts_payment_time
    ON payment.payment_attempts (
        payment_id,
        requested_at DESC
    );

/*
=========================================================
PAYMENT STATUS HISTORY
=========================================================
*/

CREATE TABLE payment.payment_status_history (
    payment_status_history_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    payment_id BIGINT
        NOT NULL,

    previous_status payment.payment_status,

    new_status payment.payment_status
        NOT NULL,

    reason VARCHAR(500),

    changed_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    CONSTRAINT pk_payment_status_history
        PRIMARY KEY (payment_status_history_id),

    CONSTRAINT fk_payment_status_history_payment
        FOREIGN KEY (payment_id)
        REFERENCES payment.payments (payment_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT ck_payment_status_history_change
        CHECK (
            previous_status IS NULL
            OR previous_status <> new_status
        ),

    CONSTRAINT ck_payment_status_history_reason
        CHECK (
            reason IS NULL
            OR char_length(btrim(reason)) > 0
        )
);

COMMENT ON TABLE payment.payment_status_history IS
    'Append-only audit history of payment lifecycle transitions.';

CREATE INDEX idx_payment_status_history
    ON payment.payment_status_history (
        payment_id,
        changed_at
    );

RESET ROLE;