/*
=========================================================
Retail Intelligence Platform
Migration: V011
Purpose:
  - Create append-only security and business audit events
  - Support actor, entity and correlation investigations
  - Allow runtime insertion without update or deletion
=========================================================
*/

SET ROLE retail_owner;

CREATE TABLE audit.audit_events (
    audit_event_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    actor_type VARCHAR(50)
        NOT NULL,

    actor_id VARCHAR(100),

    action VARCHAR(150)
        NOT NULL,

    entity_type VARCHAR(100)
        NOT NULL,

    entity_id VARCHAR(100),

    source_ip INET,

    correlation_id UUID,

    details JSONB,

    occurred_at TIMESTAMPTZ
        NOT NULL
        DEFAULT clock_timestamp(),

    CONSTRAINT pk_audit_events
        PRIMARY KEY (audit_event_id),

    CONSTRAINT ck_audit_actor_type
        CHECK (char_length(btrim(actor_type)) > 0),

    CONSTRAINT ck_audit_actor_id
        CHECK (
            actor_id IS NULL
            OR char_length(btrim(actor_id)) > 0
        ),

    CONSTRAINT ck_audit_action
        CHECK (char_length(btrim(action)) > 0),

    CONSTRAINT ck_audit_entity_type
        CHECK (char_length(btrim(entity_type)) > 0),

    CONSTRAINT ck_audit_entity_id
        CHECK (
            entity_id IS NULL
            OR char_length(btrim(entity_id)) > 0
        ),

    CONSTRAINT ck_audit_details_object
        CHECK (
            details IS NULL
            OR jsonb_typeof(details) = 'object'
        )
);

COMMENT ON TABLE audit.audit_events IS
    'Append-only security and business audit trail. Runtime applications may insert but cannot update or delete rows.';

COMMENT ON COLUMN audit.audit_events.actor_type IS
    'Actor category such as CUSTOMER, ADMIN, SERVICE or SYSTEM.';

COMMENT ON COLUMN audit.audit_events.actor_id IS
    'Stable identifier of the actor when one is known.';

COMMENT ON COLUMN audit.audit_events.action IS
    'Audited action such as LOGIN_SUCCEEDED, ORDER_CREATED or PAYMENT_REFUNDED.';

COMMENT ON COLUMN audit.audit_events.entity_type IS
    'Business entity category affected by the action.';

COMMENT ON COLUMN audit.audit_events.entity_id IS
    'Stable identifier of the affected entity when applicable.';

COMMENT ON COLUMN audit.audit_events.correlation_id IS
    'Request or workflow identifier used to trace activity across services.';

COMMENT ON COLUMN audit.audit_events.details IS
    'Non-secret contextual metadata. Passwords, tokens and payment credentials must never be stored here.';

/*
Investigation by affected entity.
*/

CREATE INDEX idx_audit_entity_time
    ON audit.audit_events (
        entity_type,
        entity_id,
        occurred_at DESC
    );

/*
Investigation by user, administrator or service.
*/

CREATE INDEX idx_audit_actor_time
    ON audit.audit_events (
        actor_type,
        actor_id,
        occurred_at DESC
    );

/*
Distributed request and workflow tracing.
*/

CREATE INDEX idx_audit_correlation
    ON audit.audit_events (
        correlation_id,
        occurred_at
    )
    WHERE correlation_id IS NOT NULL;

/*
JSONB investigation queries for selected structured details.
*/

CREATE INDEX idx_audit_details_gin
    ON audit.audit_events
    USING GIN (details)
    WHERE details IS NOT NULL;

/*
Runtime access is deliberately append-only.

The bootstrap does not grant retail_app access to the audit
schema, so V011 grants only the privileges required to insert.
*/

GRANT USAGE
    ON SCHEMA audit
    TO retail_app;

GRANT INSERT
    ON TABLE audit.audit_events
    TO retail_app;

GRANT USAGE, SELECT
    ON SEQUENCE audit.audit_events_audit_event_id_seq
    TO retail_app;

/*
The monitoring role may inspect audit events but cannot mutate them.
*/

GRANT SELECT
    ON TABLE audit.audit_events
    TO retail_monitor;

RESET ROLE;